language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy"
matrix:
  allow_failures:
    - python: "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
# command to run tests
script: py.test -s -vvv --cov coursera_helper --cov-report html --cov-report lcov

after_success:
  coveralls
